openapi: 3.0.0
info:
  title: Reservation API
  description: 店とユーザーの予約状況を確認するAPI
  version: 1.0.0

paths:
  /stores/{storeId}/reservations:
    get:
      summary: 店の予約状況を確認（月ごと）
      description: 指定した店舗の特定の月の予約状況を取得します
      parameters:
        - in: path
          name: storeId
          required: true
          schema:
            type: string
          description: 店舗のID
        - in: query
          name: year
          required: true
          schema:
            type: integer
            example: 2024
          description: 予約を確認したい年（必須）
        - in: query
          name: month
          required: true
          schema:
            type: integer
            example: 11
            minimum: 1
            maximum: 12
          description: 予約を確認したい月（1～12の範囲）
      responses:
        '200':
          description: 指定した店舗と月の予約一覧を返します
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    reservationId:
                      type: string
                      format: uuid
                      example: "123e4567-e89b-12d3-a456-426614174000"
                    from:
                      type: string
                      format: date-time
                      example: "2024-11-05T14:30:00Z"
                    to:
                      type: string
                      format: date-time
                      example: "2024-11-05T15:30:00Z"
                    status:
                      type: string
                      enum: [full, empty]
                      example: "full"

        '404':
          description: 店舗が見つからないか、指定された月の予約が存在しない場合
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: "No reservations found for this store in the specified month"

  /reservations:
    post:
      summary: 予約の作成
      description: 新しい予約を作成します
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                uuid:
                  type: string
                  example: "550e8400-e29b-41d4-a716-446655440000"
                from:
                  type: string
                  format: date-time
                  example: "2024-11-05T14:30:00Z"
                to:
                  type: string
                  format: date-time
                  example: "2024-11-05T15:30:00Z"
              required:
                - uuid
                - from
                - to
      responses:
        '201':
          description: 予約が正常に作成されました
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: "Reservation created successfully"
                  reservationId:
                    type: string
                    format: uuid
                    example: "123e4567-e89b-12d3-a456-426614174000"
        '400':
          description: リクエストのバリデーションエラー
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: "Invalid reservation data"

  /users/{uuid}/reservations:
    get:
      summary: ユーザーの予約状況を確認
      description: 特定のユーザーが行った予約を取得します
      parameters:
        - in: path
          name: uuid
          required: true
          schema:
            type: string
          description: 確認するユーザーのUUID
      responses:
        '200':
          description: 指定したユーザーの予約一覧を返します
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    reservationId:
                      type: string
                      format: uuid
                      example: "678e4567-e89b-12d3-a456-426614174000"
                    storeId:
                      type: string
                      example: "1"
                    from:
                      type: string
                      format: date-time
                      example: "2024-11-05T14:30:00Z"
                    to:
                      type: string
                      format: date-time
                      example: "2024-11-05T15:30:00Z"

        '404':
          description: 指定したユーザーの予約が見つからない場合
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: "No reservations found for this user"
