[db]
dsn="api_user:q6fYejEC@tcp(sauna-db.c540ug2ywk47.ap-northeast-1.rds.amazonaws.com:3306)/reservation_db?charset=utf8mb4&parseTime=True&loc=Local"

[cognito]
jwks_url="https://cognito-idp.ap-northeast-1.amazonaws.com/ap-northeast-1_ZigqohuSQ/.well-known/jwks.json"